### ISSUE TITLE
Fixed a bug

### ISSUE THREAD

**Issue by carolinecblaker** [philsturgeon/ee2-rest#14]
Hi Phil,

Line 191 was causing errors for me in EE 2.9.2. I changed the line to :	$params=$params.'&'.str_replace('param:', '', $key). '='. $this->EE->TMPL->parse_globals($var);

and it worked.

I forked/published this too but thought I'd tell you in case that wasn't the kosher thing to do. I don't really know what is. Cheers!

**Comment by philsturgeon** [comment]
Got a pull request for me? :)

**Comment by carolinecblaker** [comment]
I've never done that. Let me see if I can figure it out.
